In [4]:
import tensorflow as tf
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
path = "C:\\Users\\anura\\Downloads\\ML_study_jam.csv"

In [7]:
data = pd.read_csv(path)

In [15]:
print("data")
print(data)
row, column = data.shape
print("rows:",row,"columns:",column)

data
     Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
0          1.0      1659.0           1961.0                 530.0      66490.0
1          2.0      1461.0           1752.0                 210.0      39820.0
2          3.0      1340.0           1609.0                 720.0      54010.0
3          4.0      1451.0           1748.0                 620.0      53730.0
4          5.0      1770.0           2111.0                 450.0      46620.0
..         ...         ...              ...                   ...          ...
585      586.0      1227.0           1476.0                 720.0      56260.0
586      587.0      1609.0           1930.0                 740.0      76470.0
587      588.0      1553.0           1831.0                 740.0      35680.0
588      589.0      1814.0           2174.0                 770.0      90070.0
589      590.0      1240.0           1493.0                 590.0      33120.0

[590 rows x 5 columns]
rows: 590 columns: 5


In [39]:
print("Store Area mean, max, min: ",round(data["Store_Area"].mean(),-2),data["Store_Area"].max(),data["Store_Area"].min())
print("Items Available mean, max, min: ",round(data["Items_Available"].mean(),-2),data["Items_Available"].max(),data["Items_Available"].min())
print("Daily Customer Count mean, max, min: ",round(data["Daily_Customer_Count"].mean(),-2),data["Daily_Customer_Count"].max(),data["Daily_Customer_Count"].min())
print("Store Sales mean, max, min: ",round(data["Store_Sales"].mean(),-2),data["Store_Sales"].max(),data["Store_Sales"].min())

Store Area mean, max, min:  1500.0 2229.0 0.0
Items Available mean, max, min:  1800.0 2667.0 0.0
Daily Customer Count mean, max, min:  800.0 1530.0 0.0
Store Sales mean, max, min:  58200.0 102920.0 0.0


In [30]:
head = data.columns
headers = []
for i in head:
    headers.append(i)
print("headers: ",headers)

headers:  ['Store ID ', 'Store_Area', 'Items_Available', 'Daily_Customer_Count', 'Store_Sales']


In [47]:
print("Input: ",headers[:-1])
print("Output: ",headers[-1])
inputData = []
outputData = []
for i in range(row):
    tmp = []
    for j in headers[:-1]:
        tmp.append(data[j][i])
    tmp = np.array(tmp)
    inputData.append(tmp)
    outputData.append(np.array([data["Store_Sales"][i]]))
inputData = np.array(inputData)
outputData = np.array(outputData)
print("\n\nInput Data (top 10 rows):")
print(inputData[:10])
print("\n\nOutput Data (top 10 rows):")
print(outputData[:10])
print("\n\nInput shape, Output shape: ",inputData.shape,outputData.shape)

Input:  ['Store ID ', 'Store_Area', 'Items_Available', 'Daily_Customer_Count']
Output:  Store_Sales


Input Data (top 10 rows):
[[1.000e+00 1.659e+03 1.961e+03 5.300e+02]
 [2.000e+00 1.461e+03 1.752e+03 2.100e+02]
 [3.000e+00 1.340e+03 1.609e+03 7.200e+02]
 [4.000e+00 1.451e+03 1.748e+03 6.200e+02]
 [5.000e+00 1.770e+03 2.111e+03 4.500e+02]
 [6.000e+00 1.442e+03 1.733e+03 7.600e+02]
 [7.000e+00 1.542e+03 1.858e+03 1.030e+03]
 [8.000e+00 1.261e+03 1.507e+03 1.020e+03]
 [9.000e+00 1.090e+03 1.321e+03 6.800e+02]
 [1.000e+01 1.030e+03 1.235e+03 1.130e+03]]


Output Data (top 10 rows):
[[66490.]
 [39820.]
 [54010.]
 [53730.]
 [46620.]
 [45260.]
 [72240.]
 [37720.]
 [46310.]
 [44150.]]


Input shape, Output shape:  (590, 4) (590, 1)
